# Generated by Django 5.1.3 on 2024-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('lifespan', models.CharField(blank=True, max_length=100, null=True)),
                ('ideal_conditions', models.TextField(blank=True, null=True)),
                ('home_remedies', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
