# Generated by Django 5.1.3 on 2024-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='binomial_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='companions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='growing_degree_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='row_spacing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sowing_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spread',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sun_requirements',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='taxon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
