"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-es-pe3-1&ghmz5#7pf&z-e45dj9#hlaq+!!^fo@a-t(iy(x%2&'
DEBUG = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3002",  # Local frontend URL
    "https://gardeningassistant.vercel.app",  # Vercel frontend URL
]

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Add your production domain when deploying

TREFLE_API_KEY = 'jrE9AHq6X_edZPXUZM70HFxnlKF3QtLENCdOs51yYQ4'

BUILD_DIR = os.path.join(BASE_DIR, 'Gardening-Assisstance-frontend', 'gardening-assisstance-frontend', 'build', 'public')

STATIC_URL = '/static/'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'plants',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BUILD_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STATICFILES_DIRS = [
    BASE_DIR / "gardening-assistance-frontend/gardening-assisstance-frontend/build/static",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
